const TAB_ROUTE = {
  EXPLORER: 'EXPLORER',
  WATCH_LIST: 'WATCH_LIST',
  FAVORITE: 'FAVORITE',
}

const APP_ROUTE = {
  TOKEN_DETAIL: 'TOKEN_DETAIL',
  SCAN_QR: 'SCAN_QR',
}

const ROUTES = {
  ONBOARDING: 'ONBOARDING',
  MAIN: 'MAIN',
  TAB_ROUTE,
  APP_ROUTE,
}

export { APP_ROUTE, ROUTES }
